            - ชื่อ: ตั้งค่าสภาพแวดล้อม Node.js
  ใช้: actions/setup-node@v4.0.3
  กับ:
    # ตั้งค่า always-auth ใน npmrc
    always-auth: # ตัวเลือก ค่าเริ่มต้นคือ false
    # เวอร์ชัน ข้อมูลจำเพาะของเวอร์ชันที่จะใช้ ตัวอย่าง: 12.x, 10.15.1, >=10.15.0
    เวอร์ชันโหนด: # ตัวเลือก
    # ไฟล์ที่ประกอบด้วยข้อมูลจำเพาะของเวอร์ชันที่จะใช้ ตัวอย่าง: package.json, .nvmrc, .node-version, .tool-versions
    ไฟล์ node-version: # ตัวเลือก
    # สถาปัตยกรรมเป้าหมายสำหรับ Node ที่จะใช้ ตัวอย่าง: x86, x64 จะใช้สถาปัตยกรรมระบบตามค่าเริ่มต้น
    สถาปัตยกรรม: # ตัวเลือก
    # ตั้งค่าตัวเลือกนี้หากคุณต้องการให้การดำเนินการตรวจสอบเวอร์ชันล่าสุดที่มีอยู่ซึ่งตรงตามข้อกำหนดเวอร์ชัน
    ตรวจสอบล่าสุด: # ตัวเลือก
    # รีจิสทรีเสริมสำหรับการตั้งค่าการรับรองความถูกต้อง จะตั้งค่ารีจิสทรีในไฟล์ .npmrc และ .yarnrc ในระดับโครงการ และตั้งค่าการรับรองความถูกต้องเพื่ออ่านข้อมูลจาก env.NODE_AUTH_TOKEN
    registry-url: # ตัวเลือก
    # ขอบเขตเสริมสำหรับการรับรองความถูกต้องกับรีจิสทรีที่มีขอบเขต จะย้อนกลับไปยังเจ้าของที่เก็บข้อมูลเมื่อใช้รีจิสทรี GitHub Packages (https://npm.pkg.github.com/)
    ขอบเขต: # ตัวเลือก
    # ใช้ในการดึงข้อมูลการแจกจ่ายโหนดจากเวอร์ชันโหนด เนื่องจากมีค่าเริ่มต้น จึงมักไม่ได้ระบุโดยผู้ใช้ เมื่อเรียกใช้การดำเนินการนี้บน github.com ค่าเริ่มต้นก็เพียงพอแล้ว เมื่อเรียกใช้บน GHES คุณสามารถส่งโทเค็นการเข้าถึงส่วนบุคคลสำหรับ github.com ได้หากคุณประสบปัญหาการจำกัดอัตรา
    โทเค็น: # ตัวเลือก ค่าเริ่มต้นคือ ${{ github.server_url == 'https://github.com' && github.token || '' }}
    # ใช้เพื่อระบุตัวจัดการแพ็กเกจสำหรับการแคชในไดเร็กทอรีเริ่มต้น ค่าที่รองรับ: npm, yarn, pnpm
    แคช: # ตัวเลือก
    # ใช้เพื่อระบุเส้นทางไปยังไฟล์การอ้างอิง: package-lock.json, yarn.lock เป็นต้น รองรับไวด์การ์ดหรือรายชื่อไฟล์เพื่อแคชการอ้างอิงหลายรายการ
    เส้นทางการพึ่งพาแคช: # ตัวเลือก
          
